# Generated by Django 6.0.5 on 2026-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "league_table",
            "0014_leagueseasonconfig_allow_officials_to_register_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="show_player_names_in_gameday_statistics",
            field=models.BooleanField(
                default=False,
                help_text="Wenn WAHR, dann werden die Klartext Namen der Spieler in der Spieltags Statistik angezeigt",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="show_player_names_in_season_statistics",
            field=models.BooleanField(
                default=False,
                help_text="Wenn WAHR, dann werden die Klartext Namen der Spieler in der Saison Statistik angezeigt",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="top_n_players_in_gameday_statistics",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Anzahl der Top N Spieler in der Spieltags Statistik",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="top_n_players_in_season_statistics",
            field=models.PositiveSmallIntegerField(
                default=10, help_text="Anzahl der Top N Spieler in der Saison Statistik"
            ),
        ),
    ]
