# Generated by Django 6.0.8 on 2026-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "league_table",
            "0015_leagueseasonconfig_show_player_names_in_gameday_statistics_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="check_officials_automatically",
            field=models.BooleanField(
                default=False,
                help_text="Schaltet die automatische Prüfung der Offiziellen-Besetzung pro Spiel ein/aus. Die nachfolgenden Felder funktionieren nur, wenn dieses gecheckt ist",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="min_officials_f1_per_game",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Mindestanzahl an Offiziellen pro Spiel mit F1-Lizenz",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="min_officials_f2_per_game",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Mindestanzahl an Offiziellen pro Spiel mit mindestens F2-Lizenz",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="min_officials_f3_per_game",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Mindestanzahl an Offiziellen pro Spiel mit mindestens F3-Lizenz",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="min_officials_f4_per_game",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Mindestanzahl an Offiziellen pro Spiel mit mindestens F4-Lizenz",
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="min_officials_per_game",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Mindestanzahl an Offiziellen pro Spiel mit irgendeiner gültigen Lizenz (F1-F4)",
            ),
        ),
    ]
