# Generated by Django 6.0.8 on 2026-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "league_table",
            "0015_leagueseasonconfig_show_player_names_in_gameday_statistics_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="table_mode",
            field=models.CharField(
                choices=[
                    ("default", "Standard (alle Spieltage zählen)"),
                    ("top_n_gamedays", "Top N Spieltage je Team"),
                    ("top_n_games", "Top N Spiele je Team"),
                ],
                default="default",
                help_text="Wie die Tabelle berechnet wird. Standard berücksichtigt alle (nicht ausgeschlossenen) Spieltage, wie bisher.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="table_mode_top_n",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nur relevant, wenn table_mode ungleich Standard ist: Anzahl der besten Spieltage/Spiele je Team.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
