# Generated by Django 6.0.8 on 2026-09-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league_table", "0016_leagueseasonconfig_table_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueTableMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("default", "Standard (alle Spieltage zählen)"),
                            ("top_n_gamedays", "Top N Spieltage je Team"),
                            ("top_n_games", "Top N Spiele je Team"),
                        ],
                        default="default",
                        help_text="Wie die Tabelle berechnet wird. Standard berücksichtigt alle (nicht ausgeschlossenen) Spieltage, wie bisher.",
                        max_length=20,
                    ),
                ),
                (
                    "top_n",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nur relevant, wenn mode ungleich Standard ist: Anzahl der besten Spieltage/Spiele je Team.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="leagueseasonconfig",
            name="table_mode_top_n",
        ),
        # A plain RemoveField + AddField (not AlterField) on purpose: the old
        # `table_mode` is a CharField, the new one an integer FK column of the
        # same name. AlterField would have Django try to copy the *old string
        # value* (e.g. "default") straight into the new `table_mode_id`
        # integer column, which is meaningless/corrupt on any real database
        # that already has this column populated. Dropping the old column and
        # adding the new one as NULL is exactly equivalent in practice, since
        # a null `table_mode` FK means "default" too (see
        # `LeagueSeasonConfig.get_table_mode()`), and "default" was the only
        # value this field could have had before this feature ever shipped.
        migrations.RemoveField(
            model_name="leagueseasonconfig",
            name="table_mode",
        ),
        migrations.AddField(
            model_name="leagueseasonconfig",
            name="table_mode",
            field=models.ForeignKey(
                blank=True,
                help_text="Kein Eintrag = Standard (alle Spieltage zählen), wie bisher.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="league_table.leaguetablemode",
            ),
        ),
    ]
