# Generated by Django 6.0.8 on 2026-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0042_publish_legacy_draft_gamedays"),
        (
            "league_table",
            "0016_leagueseasonconfig_check_officials_automatically_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="leagueseasonconfig",
            constraint=models.UniqueConstraint(
                fields=("league", "season"),
                name="unique_leagueseasonconfig_per_league_season",
            ),
        ),
    ]
