MATCHREPORT_GAMEDAY_LIST = "matchreport-gameday-list"
MATCHREPORT_GAMEDAY_LEAGUE_STATISTICS = "matchreport-gameday-statistics"
MATCHREPORT_GAMEDAY_LIST_AND_YEAR = "matchreport-gameday-list-and-year"
MATCHREPORT_GAMEDAY_LIST_AND_YEAR_AND_LEAGUE = "matchreport-gameday-list-and-year-and-league"
MATCHREPORT_GAMEDAY_DETAIL = "matchreport-gameday-detail"