# Generated by Django 6.0.3 on 2026-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueseasonfinancialconfig",
            name="expected_gamedays_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Used for Gameday model"
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonfinancialconfig",
            name="expected_teams_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Used for Season model"
            ),
        ),
        migrations.AddField(
            model_name="leagueseasonfinancialconfig",
            name="expected_teams_per_gameday",
            field=models.PositiveIntegerField(
                default=0, help_text="Used for Gameday model"
            ),
        ),
    ]
