# Generated by Django 5.2.7 on 2026-03-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0002_leagueseasonfinancialconfig_expected_gamedays_count_and_more",
        ),
        ("gamedays", "0031_migrate_gameinfo_status_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueseasondiscount",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="If null, the discount applies to all teams in this config.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamedays.team",
            ),
        ),
        migrations.AlterField(
            model_name="leagueseasonfinancialconfig",
            name="league",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamedays.league",
            ),
        ),
        migrations.AlterField(
            model_name="leagueseasonfinancialconfig",
            name="season",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamedays.season",
            ),
        ),
    ]
