# Generated by Django 6.0.3 on 2026-03-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_leagueseasondiscount_team_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueseasondiscount",
            name="team",
        ),
    ]
