# Generated by Django 6.0.5 on 2026-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0034_remove_gameday_gamedays_ga_id_167c15_idx_and_more'),
        ('officials', '0013_alter_official_team'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='official',
            name='officials_o_id_f573ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='official',
            name='officials_o_id_72c331_idx',
        ),
        migrations.AddIndex(
            model_name='official',
            index=models.Index(fields=['team'], name='officials_o_team_id_153295_idx'),
        ),
        migrations.AddIndex(
            model_name='official',
            index=models.Index(fields=['association'], name='officials_o_associa_8f53eb_idx'),
        ),
    ]
