# Generated by Django 6.0.5 on 2026-05-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0014_optimize_database_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='official',
            new_name='officials_o_team_id_153295_idx',
            old_name='officials_official_team_idx',
        ),
        migrations.RenameIndex(
            model_name='official',
            new_name='officials_o_associa_8f53eb_idx',
            old_name='officials_official_association_idx',
        ),
    ]
