# Generated by Django 6.0.7 on 2026-07-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officials", "0014_remove_official_officials_o_id_f573ca_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodleRememberToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selector",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("validator_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "official",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="officials.official",
                    ),
                ),
            ],
        ),
    ]
