# Generated by manually on 2026-02-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0027_alter_gameresult_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameinfo",
            name="final_score",
        ),
        migrations.RemoveField(
            model_name="gameinfo",
            name="halftime_score",
        ),
        migrations.RemoveField(
            model_name="gameinfo",
            name="is_locked",
        ),
    ]
