# Generated by Django 6.0.5 on 2026-05-30 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0033_alter_team_location'),
        ('league_table', '0015_leagueseasonconfig_show_player_names_in_gameday_statistics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gameday',
            name='gamedays_ga_id_167c15_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameinfo',
            name='gamedays_ga_id_5c5d8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameinfo',
            name='gamedays_ga_id_26afd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameresult',
            name='gamedays_ga_id_e28311_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameresult',
            name='gamedays_ga_id_55dc8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameresult',
            name='gamedays_ga_id_f40410_idx',
        ),
        migrations.AddIndex(
            model_name='gameday',
            index=models.Index(fields=['date'], name='gamedays_ga_date_4d6839_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinfo',
            index=models.Index(fields=['officials'], name='gamedays_ga_officia_fdb735_idx'),
        ),
        migrations.AddIndex(
            model_name='gameinfo',
            index=models.Index(fields=['gameday'], name='gamedays_ga_gameday_3eb796_idx'),
        ),
        migrations.AddIndex(
            model_name='gameresult',
            index=models.Index(fields=['gameinfo', 'isHome'], name='gamedays_ga_gameinf_6a2d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='gameresult',
            index=models.Index(fields=['gameinfo'], name='gamedays_ga_gameinf_20cf44_idx'),
        ),
        migrations.AddIndex(
            model_name='gameresult',
            index=models.Index(fields=['team'], name='gamedays_ga_team_id_3bd340_idx'),
        ),
    ]
