# Generated by Django 6.0.5 on 2026-05-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0034_optimize_database_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gameday',
            new_name='gamedays_ga_date_4d6839_idx',
            old_name='gamedays_gameday_date_idx',
        ),
        migrations.RenameIndex(
            model_name='gameinfo',
            new_name='gamedays_ga_officia_fdb735_idx',
            old_name='gamedays_gameinfo_officials_idx',
        ),
        migrations.RenameIndex(
            model_name='gameinfo',
            new_name='gamedays_ga_gameday_3eb796_idx',
            old_name='gamedays_gameinfo_gameday_idx',
        ),
        migrations.RenameIndex(
            model_name='gameresult',
            new_name='gamedays_ga_gameinf_6a2d5e_idx',
            old_name='gamedays_gameresult_gameinfo_ishome_idx',
        ),
        migrations.RenameIndex(
            model_name='gameresult',
            new_name='gamedays_ga_gameinf_20cf44_idx',
            old_name='gamedays_gameresult_gameinfo_idx',
        ),
        migrations.RenameIndex(
            model_name='gameresult',
            new_name='gamedays_ga_team_id_3bd340_idx',
            old_name='gamedays_gameresult_team_idx',
        ),
    ]
