# Generated by Django 6.0.5 on 2026-06-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0034_remove_gameday_gamedays_ga_id_167c15_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL welche auf der Gameday Seite sichtbar sein soll",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Beschreibung der URL", max_length=50),
                ),
                (
                    "gameday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamedays.gameday",
                    ),
                ),
            ],
        ),
    ]
