# Generated by Django 6.0.7 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0035_resourceurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameday",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
