# Generated by Django 6.0.5 on 2026-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0037_tournament_tournamentrow_tournamentcolumn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="show_league_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="show_field",
            field=models.BooleanField(default=False),
        ),
    ]
