# Generated by Django 6.0.5 on 2026-07-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0038_tournament_show_league_name_tournament_show_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceurl",
            name="gameday",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamedays.gameday",
            ),
        ),
        migrations.AddField(
            model_name="resourceurl",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gamedays.tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceurl",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("gameday__isnull", False), ("tournament__isnull", True))
                    | models.Q(("gameday__isnull", True), ("tournament__isnull", False))
                ),
                name="resourceurl_exactly_one_parent",
            ),
        ),
    ]
