# Generated by Django 6.0.7 on 2026-08-15 09:39

import gamedays.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedays', '0042_publish_legacy_draft_gamedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlog',
            name='created_time',
            field=models.TimeField(default=gamedays.models.local_now_time),
        ),
    ]
