# Generated by Django 6.0.8 on 2026-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0042_publish_legacy_draft_gamedays"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teamlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
