# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0042_publish_legacy_draft_gamedays"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameinfo",
            name="day_offset",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
