# Generated by Django 6.0.8 on 2026-10-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0043_gameinfo_updated_at_gameresult_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameinfo",
            name="designer_node_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
