# Generated by Django 6.0.8 on 2026-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamedays", "0044_gameinfo_designer_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
