# Generated by Django 6.0.3 on 2026-03-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameday_designer", "0004_set_existing_templates_global"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduletemplate",
            name="sharing",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private"),
                    ("ASSOCIATION", "Association"),
                    ("GLOBAL", "Global"),
                ],
                default="GLOBAL",
                max_length=20,
            ),
        ),
    ]
